[package]
name = "e4code"
version = "0.1.0"
edition = "2024"

[dependencies]
syntect = { version = "5.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"
gtk4 = { version = "0.10" }
gio = "0.21"
glib = "0.21"
regex = "1"
